/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import Variables.cliente;
import Variables.conexion;
import Variables.envio;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maira Pinilla
 */
public class Reportes extends javax.swing.JFrame {
    conexion connet = new conexion();
    java.sql.Connection con = connet.getConexion();
    PreparedStatement ps = null;
    ResultSet rs = null;
    DefaultTableModel modelo;

    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
    }
/** void listartable() {
        try {
  
            ps = con.prepareStatement("SELECT u.Id_envio, u.Ciudad_origen, u.Ciudad_destino, c.nombreCompleto, u.nombreD , u.Direccion, u.Observaciones FROM envio u INNER JOIN cliente c ON u.Id_Cliente = c.identificacion");
            rs = ps.executeQuery();
            Object[] reporte = new Object[7];
            modelo = (DefaultTableModel) jreporte.getModel();

            while (rs.next()) {
                reporte[0] = rs.getInt("u.Id_envio");
                reporte[1] = rs.getString("u.Ciudad_origen");
                reporte[2] = rs.getString("u.Ciudad_destino");
                reporte[3] = rs.getString("c.nombreCompleto");
                reporte[4] = rs.getString("u.nombreD");
                reporte[5] = rs.getString("u.Direccion");
                reporte[6] = rs.getString("u.Observaciones");
                modelo.addRow(reporte);
            }
            jreporte.setModel(modelo);

            modelo.fireTableDataChanged();
        } catch (SQLException ex) {
            Logger.getLogger(envio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtenvio = new javax.swing.JTextField();
        btnsalir = new javax.swing.JButton();
        brnconsultar = new javax.swing.JButton();
        btnvolveramenu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jreporte = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Reporte de envios");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Id Envio:");

        btnsalir.setBackground(new java.awt.Color(1, 130, 130));
        btnsalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        brnconsultar.setBackground(new java.awt.Color(1, 130, 130));
        brnconsultar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        brnconsultar.setText("Consultar");
        brnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnconsultarActionPerformed(evt);
            }
        });

        btnvolveramenu.setBackground(new java.awt.Color(1, 130, 130));
        btnvolveramenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnvolveramenu.setText("Regresar al menú");
        btnvolveramenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolveramenuActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Reportes"));

        jLabel3.setText("Mi transporte S.A.");

        jreporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id envio", "Origen", "Destino", "Remitente", "Destinatario", "Dirección", "Observaciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jreporte);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnvolveramenu)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(118, 118, 118))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(brnconsultar)
                        .addGap(18, 18, 18)
                        .addComponent(btnsalir)
                        .addGap(46, 46, 46))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(30, 30, 30)
                        .addComponent(txtenvio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnvolveramenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtenvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brnconsultar)
                    .addComponent(btnsalir))
                .addGap(35, 35, 35)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void brnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnconsultarActionPerformed
        // TODO add your handling code here:
          // listartable();
      
       String Id = txtenvio.getText();
               String where = "";
               
               if(!"".equals(Id)){
                   
                   where = "WHERE Id_envio = '" + Id + "'";
               }
  
       String reportesql = "SELECT Id_envio, Ciudad_origen, Ciudad_destino, Id_Cliente,Identificacion_D, Direccion, Observaciones  FROM envio " + where;
       
        System.out.println(reportesql);
        Statement st;
       
       DefaultTableModel model = new DefaultTableModel();
       
               model.addColumn("Id_envio"); 
               model.addColumn("Ciudad_origen");                 
               model.addColumn("Ciudad_destino");
               model.addColumn("Id_Cliente");
               model.addColumn("Identificacion_D");
               model.addColumn("Direccion");
               model.addColumn("Observaciones");
               jreporte.setModel(model);
               
               String[] dato = new String[7];
 
               try{
                   
                   st = con.createStatement();
                   ResultSet resul = st.executeQuery(reportesql);
                   
                   while(resul.next()){
                       dato[0]=resul.getString(1);
                       dato[1]=resul.getString(2);
                       dato[2]=resul.getString(3);
                       dato[3]=resul.getString(4);
                       dato[4]=resul.getString(5);
                       dato[5]=resul.getString(6);
                       dato[6]=resul.getString(7);
                       model.addRow(dato);
                   }
       
               }catch(SQLException e){
                e.printStackTrace();   
               }
         

    }//GEN-LAST:event_brnconsultarActionPerformed

    private void btnvolveramenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolveramenuActionPerformed
        // TODO add your handling code here:
        VentanaPrincial menu = new VentanaPrincial();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnvolveramenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnconsultar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton btnvolveramenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jreporte;
    private javax.swing.JTextField txtenvio;
    // End of variables declaration//GEN-END:variables
}
